mem_test: main.cc memory_usage.h new_delete_redefine.h
	g++ ./main.cc --std=c++11 -o mem_test


clean: mem_test
	rm ./mem_test

all: mem_test
	g++ ./main.cc --std=c++11 -o 

run: mem_test
	./mem_test

